-file("/home/sea/.asdf/installs/erlang/27.2.4/lib/parsetools-2.6/include/leexinc.hrl", 0).
%% The source of this file is part of leex distribution, as such it
%% has the same Copyright as the other files in the leex
%% distribution. The Copyright is defined in the accompanying file
%% COPYRIGHT. However, the resultant scanner generated by leex is the
%% property of the creator of the scanner and is not covered by that
%% Copyright.

-module(obr_lexer).

-export([string/1,string/2,token/2,token/3,tokens/2,tokens/3]).
-export([format_error/1]).

%% User code. This is placed here to allow extra attributes.
-file("./priv/obr_lexer.xrl", 221).

id_validate(Chars, Line) ->
  case length(Chars) > 40 of
    true ->
      io:format("WARNING: Identifier too long. ~w: ~s -> ~s~n", [Line, Chars, lists:sublist(Chars, 40)]),
      lists:sublist(Chars, 40);
    _Else ->
      Chars
  end.

int_validate(Chars, _Line) -> int_validate_del_zero(Chars).
int_validate_del_zero([$0] = Chars) -> Chars;
int_validate_del_zero([$0|Chars]) -> int_validate_del_zero(Chars);
int_validate_del_zero(Chars) -> Chars.

intwr_validate(Chars, Line) ->
  io:format("WARNING: A hexadecimal literal hasn't a trailing H. ~w: ~s -> ~s~n", [Line, Chars, Chars]),
  int_validate(Chars, Line).

str_validate(Chars, _Line) -> Chars.

-file("/home/sea/.asdf/installs/erlang/27.2.4/lib/parsetools-2.6/include/leexinc.hrl", 14).

format_error({illegal,S}) -> ["illegal characters ",io_lib:write_string(S)];
format_error({user,S}) -> S.

%% string(InChars) ->
%% string(InChars, Loc) ->
%% {ok,Tokens,EndLoc} | {error,ErrorInfo,EndLoc}.
%% Loc is the starting location of the token, while EndLoc is the first not scanned
%% location. Location is either Line or {Line,Column}, depending on the "error_location" option.

string(Ics) -> 
    string(Ics,1).
string(Ics,L0) -> 
    string(Ics, L0, 1, Ics, []).
string(Ics, L0, C0, Tcs, Ts) -> 
    case do_string(Ics, L0, C0, Tcs, Ts) of
        {ok, T, {L,_}} -> {ok, T, L};
        {error, {{EL,_},M,D}, {L,_}} ->
            EI = {EL,M,D},
            {error, EI, L}
    end.

do_string([], L, C, [], Ts) ->                     % No partial tokens!
    {ok,yyrev(Ts),{L,C}};
do_string(Ics0, L0, C0, Tcs, Ts) ->
    case yystate(yystate(), Ics0, L0, C0, 0, reject, 0) of
        {A,Alen,Ics1,L1,_C1} ->                  % Accepting end state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {A,Alen,Ics1,L1,_C1,_S1} ->              % Accepting transition state
            C2 = adjust_col(Tcs, Alen, C0),
            string_cont(Ics1, L1, C2, yyaction(A, Alen, Tcs, L0, C0), Ts);
        {reject,_Alen,Tlen,_Ics1,_L1,_C1,_S1} ->  % After a non-accepting state
            {error,{{L0, C0} ,?MODULE,{illegal,yypre(Tcs, Tlen+1)}},{L0, C0}};
        {A,Alen,Tlen,_Ics1,L1, C1,_S1}->
            Tcs1 = yysuf(Tcs, Alen),
            L2 = adjust_line(Tlen, Alen, Tcs1, L1),
            C2 = adjust_col(Tcs, Alen, C1),
            string_cont(Tcs1, L2, C2, yyaction(A, Alen, Tcs, L0,C0), Ts)
    end.

%% string_cont(RestChars, Line, Col, Token, Tokens)
%% Test for and remove the end token wrapper. Push back characters
%% are prepended to RestChars.

-dialyzer({nowarn_function, string_cont/5}).

string_cont(Rest, Line, Col, {token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    do_string(Rest, Line, Col, Rest, [T|Ts]);
string_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, [T|Ts]);
string_cont(Rest, Line, Col, skip_token, Ts) ->
    do_string(Rest, Line, Col, Rest, Ts);
string_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    do_string(NewRest, Line, Col, NewRest, Ts);
string_cont(_Rest, Line, Col, {error,S}, _Ts) ->
    {error,{{Line, Col},?MODULE,{user,S}},{Line,Col}}.

%% token(Continuation, Chars) ->
%% token(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {token,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCol,AccAction,AccLen}

token(Cont,Chars) -> 
    token(Cont,Chars,1).
token(Cont, Chars, Line) -> 
    case do_token(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_token([], Chars, Line, Col) ->
    token(yystate(), Chars, Line, Col, Chars, 0, Line, Col, reject, 0);
do_token({token,State,Line,Col,Tcs,Tlen,Tline,Tcol,Action,Alen}, Chars, _, _) ->
    token(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Action, Alen).

%% token(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% The argument order is chosen to be more efficient.

token(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Alen1,Tline,Tcol,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            token_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol));
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{token,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     true -> {eof,{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,Ics1,_L1,_C1,_S1} ->    % No token match
            Error = {{Tline,Tcol},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            {done,{error,Error,{Tline,Tcol}},Ics1};
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->       % Use last accept match
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            token_cont(Tcs1, L2, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol))
    end.

%% token_cont(RestChars, Line, Col, Token)
%% If we have a token or error then return done, else if we have a
%% skip_token then continue.

-dialyzer({nowarn_function, token_cont/4}).

token_cont(Rest, Line, Col, {token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, {end_token,T}) ->
    {done,{ok,T,{Line,Col}},Rest};
token_cont(Rest, Line, Col, {end_token,T,Push}) ->
    NewRest = Push ++ Rest,
    {done,{ok,T,{Line,Col}},NewRest};
token_cont(Rest, Line, Col, skip_token) ->
    token(yystate(), Rest, Line, Col, Rest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {skip_token,Push}) ->
    NewRest = Push ++ Rest,
    token(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, reject, 0);
token_cont(Rest, Line, Col, {error,S}) ->
    {done,{error,{{Line, Col},?MODULE,{user,S}},{Line, Col}},Rest}.

%% tokens(Continuation, Chars) ->
%% tokens(Continuation, Chars, Loc) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.
%% Must be careful when re-entering to append the latest characters to the
%% after characters in an accept. The continuation is:
%% {tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Tokens,AccAction,AccLen}
%% {skip_tokens,State,CurrLine,CurrCol,TokenChars,TokenLen,TokenLine,TokenCur,Error,AccAction,AccLen}

tokens(Cont,Chars) -> 
    tokens(Cont,Chars,1).
tokens(Cont, Chars, Line) -> 
    case do_tokens(Cont,Chars,Line,1) of
        {more, _} = C -> C;
        {done, Ret0, R} ->
            Ret1 = case Ret0 of
                {ok, T, {L,_}} -> {ok, T, L};
                {eof, {L,_}} -> {eof, L};
                {error, {{EL,_},M,D},{L,_}} -> {error, {EL,M,D},L}
            end,
            {done, Ret1, R}
    end.

do_tokens([], Chars, Line, Col) ->
    tokens(yystate(), Chars, Line, Col, Chars, 0, Line, Col, [], reject, 0);
do_tokens({tokens,State,Line,Col,Tcs,Tlen,Tline,Tcol,Ts,Action,Alen}, Chars, _,_) ->
    tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Ts, Action, Alen);
do_tokens({skip_tokens,State,Line, Col, Tcs,Tlen,Tline,Tcol,Error,Action,Alen}, Chars, _,_) ->
    skip_tokens(State, Chars, Line, Col, Tcs ++ Chars, Tlen, Tline, Tcol, Error, Action, Alen).

%% tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol,Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Ts, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        %% Accepting end state, we have a token.
        {A1,Alen1,Ics1,L1,C1} ->
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline, Tcol), Ts);
        %% Accepting transition state, can take more chars.
        {A1,Alen1,[],L1,C1,S1} ->                  % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Ts,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->               % Take what we got
            C2 = adjust_col(Tcs, Alen1, C1),
            tokens_cont(Ics1, L1, C2, yyaction(A1, Alen1, Tcs, Tline,Tcol), Ts);
        %% After a non-accepting state, maybe reach accept state later.
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->            % Need more chars to check
            {more,{tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Ts,A1,Alen1}};
        {reject,_Alen1,Tlen1,eof,L1,C1,_S1} ->     % No token match
            %% Check for partial token which is error, no need to skip here.
            Ret = if Tlen1 > 0 -> {error,{{Tline,Tcol},?MODULE,
                                          %% Skip eof tail in Tcs.
                                          {illegal,yypre(Tcs, Tlen1)}},{L1,C1}};
                     Ts == [] -> {eof,{L1,C1}};
                     true -> {ok,yyrev(Ts),{L1,C1}}
                  end,
            {done,Ret,eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            %% Skip rest of tokens.
            Error = {{L1,C1},?MODULE,{illegal,yypre(Tcs, Tlen1+1)}},
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1, Error);
        {A1,Alen1,Tlen1,_Ics1,L1,_C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline,Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            C2 = C0 + Alen1,
            tokens_cont(Tcs1, L2, C2, Token, Ts)
    end.

%% tokens_cont(RestChars, Line, Column, Token, Tokens)
%% If we have an end_token or error then return done, else if we have
%% a token then save it and continue, else if we have a skip_token
%% just continue.

-dialyzer({nowarn_function, tokens_cont/5}).

tokens_cont(Rest, Line, Col, {token,T}, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, [T|Ts], reject, 0);
tokens_cont(Rest, Line, Col, {end_token,T}, Ts) ->
    {done,{ok,yyrev(Ts, [T]),{Line,Col}},Rest};
tokens_cont(Rest, Line, Col, {end_token,T,Push}, Ts) ->
    NewRest = Push ++ Rest,
    {done,{ok,yyrev(Ts, [T]),{Line, Col}},NewRest};
tokens_cont(Rest, Line, Col, skip_token, Ts) ->
    tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {skip_token,Push}, Ts) ->
    NewRest = Push ++ Rest,
    tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Ts, reject, 0);
tokens_cont(Rest, Line, Col, {error,S}, _Ts) ->
    skip_tokens(Rest, Line, Col, {{Line,Col},?MODULE,{user,S}}).

%% skip_tokens(InChars, Line, Col, Error) -> {done,{error,Error,{Line,Col}},Ics}.
%% Skip tokens until an end token, junk everything and return the error.

skip_tokens(Ics, Line, Col, Error) ->
    skip_tokens(yystate(), Ics, Line, Col, Ics, 0, Line, Col, Error, reject, 0).

%% skip_tokens(State, InChars, Line, Col, TokenChars, TokenLen, TokenLine, TokenCol, Tokens,
%% AcceptAction, AcceptLen) ->
%% {more,Continuation} | {done,ReturnVal,RestChars}.

skip_tokens(S0, Ics0, L0, C0, Tcs, Tlen0, Tline, Tcol, Error, A0, Alen0) ->
    case yystate(S0, Ics0, L0, C0, Tlen0, A0, Alen0) of
        {A1,Alen1,Ics1,L1, C1} ->                  % Accepting end state
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,[],L1,C1, S1} ->                 % After an accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Alen1,Tline,Tcol,Error,A1,Alen1}};
        {A1,Alen1,Ics1,L1,C1,_S1} ->
            skip_cont(Ics1, L1, C1, yyaction(A1, Alen1, Tcs, Tline, Tcol), Error);
        {A1,Alen1,Tlen1,[],L1,C1,S1} ->           % After a non-accepting state
            {more,{skip_tokens,S1,L1,C1,Tcs,Tlen1,Tline,Tcol,Error,A1,Alen1}};
        {reject,_Alen1,_Tlen1,eof,L1,C1,_S1} ->
            {done,{error,Error,{L1,C1}},eof};
        {reject,_Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            skip_tokens(yysuf(Tcs, Tlen1+1), L1, C1,Error);
        {A1,Alen1,Tlen1,_Ics1,L1,C1,_S1} ->
            Token = yyaction(A1, Alen1, Tcs, Tline, Tcol),
            Tcs1 = yysuf(Tcs, Alen1),
            L2 = adjust_line(Tlen1, Alen1, Tcs1, L1),
            skip_cont(Tcs1, L2, C1, Token, Error)
    end.

%% skip_cont(RestChars, Line, Col, Token, Error)
%% Skip tokens until we have an end_token or error then return done
%% with the original rror.

-dialyzer({nowarn_function, skip_cont/5}).

skip_cont(Rest, Line, Col, {token,_T}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {end_token,_T}, Error) ->
    {done,{error,Error,{Line,Col}},Rest};
skip_cont(Rest, Line, Col, {end_token,_T,Push}, Error) ->
    NewRest = Push ++ Rest,
    {done,{error,Error,{Line,Col}},NewRest};
skip_cont(Rest, Line, Col, skip_token, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {skip_token,Push}, Error) ->
    NewRest = Push ++ Rest,
    skip_tokens(yystate(), NewRest, Line, Col, NewRest, 0, Line, Col, Error, reject, 0);
skip_cont(Rest, Line, Col, {error,_S}, Error) ->
    skip_tokens(yystate(), Rest, Line, Col, Rest, 0, Line, Col, Error, reject, 0).

-compile({nowarn_unused_function, [yyrev/1, yyrev/2, yypre/2, yysuf/2]}).

yyrev(List) -> lists:reverse(List).
yyrev(List, Tail) -> lists:reverse(List, Tail).
yypre(List, N) -> lists:sublist(List, N).
yysuf(List, N) -> lists:nthtail(N, List).

%% adjust_line(TokenLength, AcceptLength, Chars, Line) -> NewLine
%% Make sure that newlines in Chars are not counted twice.
%% Line has been updated with respect to newlines in the prefix of
%% Chars consisting of (TokenLength - AcceptLength) characters.

-compile({nowarn_unused_function, adjust_line/4}).

adjust_line(N, N, _Cs, L) -> L;
adjust_line(T, A, [$\n|Cs], L) ->
    adjust_line(T-1, A, Cs, L-1);
adjust_line(T, A, [_|Cs], L) ->
    adjust_line(T-1, A, Cs, L).

%% adjust_col(Chars, AcceptLength, Col) -> NewCol
%% Handle newlines, tabs and unicode chars.
adjust_col(_, 0, Col) ->
    Col;
adjust_col([$\n | R], L, _) ->
    adjust_col(R, L-1, 1);
adjust_col([$\t | R], L, Col) ->
    adjust_col(R, L-1, tab_forward(Col)+1);
adjust_col([C | R], L, Col) when C>=0 andalso C=< 16#7F ->
    adjust_col(R, L-1, Col+1);
adjust_col([C | R], L, Col) when C>= 16#80 andalso C=< 16#7FF ->
    adjust_col(R, L-1, Col+2);
adjust_col([C | R], L, Col) when C>= 16#800 andalso C=< 16#FFFF ->
    adjust_col(R, L-1, Col+3);
adjust_col([C | R], L, Col) when C>= 16#10000 andalso C=< 16#10FFFF ->
    adjust_col(R, L-1, Col+4).

tab_forward(C) ->
    D = C rem tab_size(),
    A = tab_size()-D,
    C+A.

tab_size() -> 8.

%% yystate() -> InitialState.
%% yystate(State, InChars, Line, Col, CurrTokLen, AcceptAction, AcceptLen) ->
%% {Action, AcceptLen, RestChars, Line, Col} |
%% {Action, AcceptLen, RestChars, Line, Col, State} |
%% {reject, AcceptLen, CurrTokLen, RestChars, Line, Col, State} |
%% {Action, AcceptLen, CurrTokLen, RestChars, Line, Col, State}.
%% Generated state transition functions. The non-accepting end state
%% return signal either an unrecognised character or end of current
%% input.

-file("./priv/obr_lexer.erl", 359).
yystate() -> 157.

yystate(160, [76|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(156, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(160, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,160};
yystate(159, [32|Ics], Line, Col, Tlen, _, _) ->
    yystate(159, Ics, Line, Col, Tlen+1, 67, Tlen);
yystate(159, [13|Ics], Line, Col, Tlen, _, _) ->
    yystate(159, Ics, Line, Col, Tlen+1, 67, Tlen);
yystate(159, [9|Ics], Line, Col, Tlen, _, _) ->
    yystate(159, Ics, Line, Col, Tlen+1, 67, Tlen);
yystate(159, [10|Ics], Line, _, Tlen, _, _) ->
    yystate(159, Ics, Line+1, 1, Tlen+1, 67, Tlen);
yystate(159, Ics, Line, Col, Tlen, _, _) ->
    {67,Tlen,Ics,Line,Col,159};
yystate(158, [85|Ics], Line, Col, Tlen, _, _) ->
    yystate(160, Ics, Line, Col, Tlen+1, 18, Tlen);
yystate(158, Ics, Line, Col, Tlen, _, _) ->
    {18,Tlen,Ics,Line,Col,158};
yystate(157, [126|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(153, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [125|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(149, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(145, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [123|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(141, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [94|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(97, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [93|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(93, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [91|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(89, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [87|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(85, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [86|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(65, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [85|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(53, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(33, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(10, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [81|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [80|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(66, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [79|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(126, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(138, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [77|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(150, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [73|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(148, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [71|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [72|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(112, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [70|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(108, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(80, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [68|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(40, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [67|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(24, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [66|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(7, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [65|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(31, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [62|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(51, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [61|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(59, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [60|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(63, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [59|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(71, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [58|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(75, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [47|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(103, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [46|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(107, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(115, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [44|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(119, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(123, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [42|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(127, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [41|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(131, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [40|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(135, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [38|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(143, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [35|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(147, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [32|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(159, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [13|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(159, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [9|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(159, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [10|Ics], Line, _, Tlen, Action, Alen) ->
    yystate(159, Ics, Line+1, 1, Tlen+1, Action, Alen);
yystate(157, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 74, C =< 76 ->
    yystate(112, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 88, C =< 90 ->
    yystate(112, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(109, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 103, C =< 122 ->
    yystate(112, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(157, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,157};
yystate(156, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(152, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(156, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,156};
yystate(155, [34|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(151, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14, C =< 33 ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 35, C =< 93 ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 95, C =< 123 ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 125 ->
    yystate(155, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(155, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,155};
yystate(154, [68|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(158, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(154, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,154};
yystate(153, Ics, Line, Col, Tlen, _, _) ->
    {39,Tlen,Ics,Line,Col};
yystate(152, Ics, Line, Col, Tlen, _, _) ->
    {17,Tlen,Ics,Line,Col};
yystate(151, Ics, Line, Col, Tlen, _, _) ->
    {64,Tlen,Ics,Line,Col};
yystate(150, [79|Ics], Line, Col, Tlen, _, _) ->
    yystate(154, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(150, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,150};
yystate(149, Ics, Line, Col, Tlen, _, _) ->
    {51,Tlen,Ics,Line,Col};
yystate(148, [83|Ics], Line, Col, Tlen, _, _) ->
    yystate(144, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(148, [78|Ics], Line, Col, Tlen, _, _) ->
    yystate(140, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(148, [77|Ics], Line, Col, Tlen, _, _) ->
    yystate(136, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(148, [70|Ics], Line, Col, Tlen, _, _) ->
    yystate(116, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(148, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,148};
yystate(147, Ics, Line, Col, Tlen, _, _) ->
    {56,Tlen,Ics,Line,Col};
yystate(146, Ics, Line, Col, Tlen, _, _) ->
    {19,Tlen,Ics,Line,Col};
yystate(145, Ics, Line, Col, Tlen, _, _) ->
    {45,Tlen,Ics,Line,Col};
yystate(144, Ics, Line, Col, Tlen, _, _) ->
    {16,Tlen,Ics,Line,Col};
yystate(143, Ics, Line, Col, Tlen, _, _) ->
    {40,Tlen,Ics,Line,Col};
yystate(142, [76|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(146, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(142, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,142};
yystate(141, [65|Ics], Line, Col, Tlen, _, _) ->
    yystate(137, Ics, Line, Col, Tlen+1, 50, Tlen);
yystate(141, Ics, Line, Col, Tlen, _, _) ->
    {50,Tlen,Ics,Line,Col,141};
yystate(140, Ics, Line, Col, Tlen, _, _) ->
    {15,Tlen,Ics,Line,Col};
yystate(139, [39|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(151, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, [11|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, [12|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 0, C =< 9 ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 14, C =< 38 ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 40, C =< 93 ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 95, C =< 123 ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 125 ->
    yystate(139, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(139, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,139};
yystate(138, [73|Ics], Line, Col, Tlen, _, _) ->
    yystate(142, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(138, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,138};
yystate(137, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(133, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(137, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,137};
yystate(136, [80|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(132, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(136, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,136};
yystate(135, Ics, Line, Col, Tlen, _, _) ->
    {46,Tlen,Ics,Line,Col};
yystate(134, Ics, Line, Col, Tlen, _, _) ->
    {20,Tlen,Ics,Line,Col};
yystate(133, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(129, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(133, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,133};
yystate(132, [79|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(128, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(132, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,132};
yystate(131, Ics, Line, Col, Tlen, _, _) ->
    {47,Tlen,Ics,Line,Col};
yystate(130, Ics, Line, Col, Tlen, _, _) ->
    {21,Tlen,Ics,Line,Col};
yystate(129, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(125, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(129, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,129};
yystate(128, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(124, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(128, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,128};
yystate(127, Ics, Line, Col, Tlen, _, _) ->
    {37,Tlen,Ics,Line,Col};
yystate(126, [82|Ics], Line, Col, Tlen, _, _) ->
    yystate(130, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(126, [70|Ics], Line, Col, Tlen, _, _) ->
    yystate(134, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(126, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,126};
yystate(125, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(121, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(125, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,125};
yystate(124, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(120, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(124, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,124};
yystate(123, Ics, Line, Col, Tlen, _, _) ->
    {35,Tlen,Ics,Line,Col};
yystate(122, Ics, Line, Col, Tlen, _, _) ->
    {22,Tlen,Ics,Line,Col};
yystate(121, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(117, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(121, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,121};
yystate(120, Ics, Line, Col, Tlen, _, _) ->
    {14,Tlen,Ics,Line,Col};
yystate(119, Ics, Line, Col, Tlen, _, _) ->
    {43,Tlen,Ics,Line,Col};
yystate(118, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(122, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(118, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,118};
yystate(117, [125|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(113, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(117, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,117};
yystate(116, Ics, Line, Col, Tlen, _, _) ->
    {13,Tlen,Ics,Line,Col};
yystate(115, Ics, Line, Col, Tlen, _, _) ->
    {36,Tlen,Ics,Line,Col};
yystate(114, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(118, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(114, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,114};
yystate(113, Ics, Line, Col, Tlen, _, _) ->
    {34,Tlen,Ics,Line,Col};
yystate(112, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col};
yystate(111, Ics, Line, Col, Tlen, _, _) ->
    {41,Tlen,Ics,Line,Col};
yystate(110, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(114, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(110, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,110};
yystate(109, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(109, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(109, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(109, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(109, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(109, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(109, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,109};
yystate(108, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, [79|Ics], Line, Col, Tlen, _, _) ->
    yystate(104, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, [65|Ics], Line, Col, Tlen, _, _) ->
    yystate(96, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, [C|Ics], Line, Col, Tlen, _, _) when C >= 66, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(108, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,108};
yystate(107, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(111, Ics, Line, Col, Tlen+1, 42, Tlen);
yystate(107, Ics, Line, Col, Tlen, _, _) ->
    {42,Tlen,Ics,Line,Col,107};
yystate(106, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(110, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(106, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,106};
yystate(105, Ics, Line, Col, Tlen, _, _) ->
    {61,Tlen,Ics,Line,Col};
yystate(104, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(100, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(104, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,104};
yystate(103, Ics, Line, Col, Tlen, _, _) ->
    {38,Tlen,Ics,Line,Col};
yystate(102, [73|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(106, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(102, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,102};
yystate(101, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(101, [104|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(101, [72|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(101, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(101, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,101};
yystate(100, Ics, Line, Col, Tlen, _, _) ->
    {12,Tlen,Ics,Line,Col};
yystate(99, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(87, Ics, Line, Col, Tlen+1, 63, Tlen);
yystate(99, [68|Ics], Line, Col, Tlen, _, _) ->
    yystate(87, Ics, Line, Col, Tlen+1, 63, Tlen);
yystate(99, [69|Ics], Line, Col, Tlen, _, _) ->
    yystate(87, Ics, Line, Col, Tlen+1, 63, Tlen);
yystate(99, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(99, Ics, Line, Col, Tlen+1, 63, Tlen);
yystate(99, Ics, Line, Col, Tlen, _, _) ->
    {63,Tlen,Ics,Line,Col,99};
yystate(98, Ics, Line, Col, Tlen, _, _) ->
    {23,Tlen,Ics,Line,Col};
yystate(97, Ics, Line, Col, Tlen, _, _) ->
    {54,Tlen,Ics,Line,Col};
yystate(96, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [104|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [76|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(92, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [72|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(96, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,96};
yystate(95, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(91, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(95, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,95};
yystate(94, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(98, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(94, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,94};
yystate(93, Ics, Line, Col, Tlen, _, _) ->
    {49,Tlen,Ics,Line,Col};
yystate(92, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(88, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(92, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,92};
yystate(91, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(91, Ics, Line, Col, Tlen+1, 63, Tlen);
yystate(91, Ics, Line, Col, Tlen, _, _) ->
    {63,Tlen,Ics,Line,Col,91};
yystate(90, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(94, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(90, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,90};
yystate(89, Ics, Line, Col, Tlen, _, _) ->
    {48,Tlen,Ics,Line,Col};
yystate(88, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(84, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(88, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,88};
yystate(87, [45|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(87, [43|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(95, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(87, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(91, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(87, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,87};
yystate(86, [85|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(90, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(86, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,86};
yystate(85, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(81, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(85, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,85};
yystate(84, Ics, Line, Col, Tlen, _, _) ->
    {11,Tlen,Ics,Line,Col};
yystate(83, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 62, Tlen);
yystate(83, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 62, Tlen);
yystate(83, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 62, Tlen);
yystate(83, [46|Ics], Line, Col, Tlen, _, _) ->
    yystate(99, Ics, Line, Col, Tlen+1, 62, Tlen);
yystate(83, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(83, Ics, Line, Col, Tlen+1, 62, Tlen);
yystate(83, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, 62, Tlen);
yystate(83, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 62, Tlen);
yystate(83, Ics, Line, Col, Tlen, _, _) ->
    {62,Tlen,Ics,Line,Col,83};
yystate(82, [68|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(86, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(82, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,82};
yystate(81, [73|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(77, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(81, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,81};
yystate(80, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, [78|Ics], Line, Col, Tlen, _, _) ->
    yystate(76, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, [76|Ics], Line, Col, Tlen, _, _) ->
    yystate(68, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(80, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,80};
yystate(79, Ics, Line, Col, Tlen, _, _) ->
    {52,Tlen,Ics,Line,Col};
yystate(78, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(82, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(78, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,78};
yystate(77, [76|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(73, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(77, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,77};
yystate(76, [68|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(72, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(76, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,76};
yystate(75, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(79, Ics, Line, Col, Tlen+1, 53, Tlen);
yystate(75, Ics, Line, Col, Tlen, _, _) ->
    {53,Tlen,Ics,Line,Col,75};
yystate(74, [67|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(78, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(74, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,74};
yystate(73, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(69, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(73, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,73};
yystate(72, Ics, Line, Col, Tlen, _, _) ->
    {10,Tlen,Ics,Line,Col};
yystate(71, Ics, Line, Col, Tlen, _, _) ->
    {44,Tlen,Ics,Line,Col};
yystate(70, [79|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(74, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(70, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,70};
yystate(69, Ics, Line, Col, Tlen, _, _) ->
    {31,Tlen,Ics,Line,Col};
yystate(68, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(64, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(68, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,68};
yystate(67, Ics, Line, Col, Tlen, _, _) ->
    {57,Tlen,Ics,Line,Col};
yystate(66, [82|Ics], Line, Col, Tlen, _, _) ->
    yystate(70, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(66, [79|Ics], Line, Col, Tlen, _, _) ->
    yystate(102, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(66, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,66};
yystate(65, [65|Ics], Line, Col, Tlen, _, _) ->
    yystate(61, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(65, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,65};
yystate(64, [73|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(60, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(64, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(52, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(64, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,64};
yystate(63, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(67, Ics, Line, Col, Tlen+1, 59, Tlen);
yystate(63, Ics, Line, Col, Tlen, _, _) ->
    {59,Tlen,Ics,Line,Col,63};
yystate(62, Ics, Line, Col, Tlen, _, _) ->
    {24,Tlen,Ics,Line,Col};
yystate(61, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(57, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(61, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,61};
yystate(60, [70|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(56, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(60, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,60};
yystate(59, Ics, Line, Col, Tlen, _, _) ->
    {55,Tlen,Ics,Line,Col};
yystate(58, [68|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(62, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(58, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,58};
yystate(57, Ics, Line, Col, Tlen, _, _) ->
    {30,Tlen,Ics,Line,Col};
yystate(56, Ics, Line, Col, Tlen, _, _) ->
    {9,Tlen,Ics,Line,Col};
yystate(55, Ics, Line, Col, Tlen, _, _) ->
    {58,Tlen,Ics,Line,Col};
yystate(54, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(58, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(54, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,54};
yystate(53, [78|Ics], Line, Col, Tlen, _, _) ->
    yystate(49, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(53, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,53};
yystate(52, [73|Ics], Line, Col, Tlen, _, _) ->
    yystate(48, Ics, Line, Col, Tlen+1, 7, Tlen);
yystate(52, Ics, Line, Col, Tlen, _, _) ->
    {7,Tlen,Ics,Line,Col,52};
yystate(51, [61|Ics], Line, Col, Tlen, _, _) ->
    yystate(55, Ics, Line, Col, Tlen+1, 60, Tlen);
yystate(51, Ics, Line, Col, Tlen, _, _) ->
    {60,Tlen,Ics,Line,Col,51};
yystate(50, [79|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(54, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(50, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,50};
yystate(49, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(45, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(49, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,49};
yystate(48, [70|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(44, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(48, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,48};
yystate(47, Ics, Line, Col, Tlen, _, _) ->
    {0,Tlen,Ics,Line,Col};
yystate(46, Ics, Line, Col, Tlen, _, _) ->
    {25,Tlen,Ics,Line,Col};
yystate(45, [73|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(41, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(45, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,45};
yystate(44, Ics, Line, Col, Tlen, _, _) ->
    {8,Tlen,Ics,Line,Col};
yystate(43, [89|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(47, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(43, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,43};
yystate(42, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(46, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(42, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,42};
yystate(41, [76|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(37, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(41, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,41};
yystate(40, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, [79|Ics], Line, Col, Tlen, _, _) ->
    yystate(36, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, [73|Ics], Line, Col, Tlen, _, _) ->
    yystate(32, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(40, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,40};
yystate(39, [65|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(43, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(39, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,39};
yystate(38, [65|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(42, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(38, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,38};
yystate(37, Ics, Line, Col, Tlen, _, _) ->
    {33,Tlen,Ics,Line,Col};
yystate(36, Ics, Line, Col, Tlen, _, _) ->
    {6,Tlen,Ics,Line,Col};
yystate(35, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(39, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(35, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,35};
yystate(34, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(38, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(34, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,34};
yystate(33, [89|Ics], Line, Col, Tlen, _, _) ->
    yystate(29, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(33, [82|Ics], Line, Col, Tlen, _, _) ->
    yystate(17, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(33, [79|Ics], Line, Col, Tlen, _, _) ->
    yystate(5, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(33, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(1, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(33, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,33};
yystate(32, [86|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(28, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(32, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,32};
yystate(31, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(31, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(31, [82|Ics], Line, Col, Tlen, _, _) ->
    yystate(35, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(31, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(31, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(31, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,31};
yystate(30, Ics, Line, Col, Tlen, _, _) ->
    {26,Tlen,Ics,Line,Col};
yystate(29, [80|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(25, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(29, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,29};
yystate(28, Ics, Line, Col, Tlen, _, _) ->
    {5,Tlen,Ics,Line,Col};
yystate(27, Ics, Line, Col, Tlen, _, _) ->
    {1,Tlen,Ics,Line,Col};
yystate(26, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(30, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(26, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,26};
yystate(25, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(21, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(25, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,25};
yystate(24, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, [79|Ics], Line, Col, Tlen, _, _) ->
    yystate(20, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, [65|Ics], Line, Col, Tlen, _, _) ->
    yystate(4, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 66, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(24, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,24};
yystate(23, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(27, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(23, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,23};
yystate(22, [82|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(26, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(22, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,22};
yystate(21, Ics, Line, Col, Tlen, _, _) ->
    {29,Tlen,Ics,Line,Col};
yystate(20, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(16, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(20, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,20};
yystate(19, [73|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(23, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(19, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,19};
yystate(18, [85|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(22, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(18, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,18};
yystate(17, [85|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(13, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(17, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,17};
yystate(16, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(12, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(16, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,16};
yystate(15, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, [104|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, [72|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, [71|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(19, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(15, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,15};
yystate(14, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(18, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(14, [80|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(34, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(14, [67|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(50, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(14, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,14};
yystate(13, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(9, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(13, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,13};
yystate(12, [84|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(8, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(12, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,12};
yystate(11, Ics, Line, Col, Tlen, _, _) ->
    {2,Tlen,Ics,Line,Col};
yystate(10, [69|Ics], Line, Col, Tlen, _, _) ->
    yystate(14, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(10, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,10};
yystate(9, Ics, Line, Col, Tlen, _, _) ->
    {28,Tlen,Ics,Line,Col};
yystate(8, Ics, Line, Col, Tlen, _, _) ->
    {4,Tlen,Ics,Line,Col};
yystate(7, [124|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [104|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [89|Ics], Line, Col, Tlen, _, _) ->
    yystate(11, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [72|Ics], Line, Col, Tlen, _, _) ->
    yystate(105, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [70|Ics], Line, Col, Tlen, _, _) ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [69|Ics], Line, Col, Tlen, _, _) ->
    yystate(15, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 65, C =< 68 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, [C|Ics], Line, Col, Tlen, _, _) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, 65, Tlen);
yystate(7, Ics, Line, Col, Tlen, _, _) ->
    {65,Tlen,Ics,Line,Col,7};
yystate(6, Ics, Line, Col, Tlen, _, _) ->
    {32,Tlen,Ics,Line,Col};
yystate(5, Ics, Line, Col, Tlen, _, _) ->
    {27,Tlen,Ics,Line,Col};
yystate(4, [124|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [104|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [83|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(0, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [72|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(105, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 48, C =< 57 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 65, C =< 70 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, [C|Ics], Line, Col, Tlen, Action, Alen) when C >= 97, C =< 102 ->
    yystate(101, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(4, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,4};
yystate(3, Ics, Line, Col, Tlen, _, _) ->
    {3,Tlen,Ics,Line,Col};
yystate(2, [78|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(6, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(2, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,2};
yystate(1, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(2, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(1, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,1};
yystate(0, [69|Ics], Line, Col, Tlen, Action, Alen) ->
    yystate(3, Ics, Line, Col, Tlen+1, Action, Alen);
yystate(0, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,0};
yystate(S, Ics, Line, Col, Tlen, Action, Alen) ->
    {Action,Alen,Tlen,Ics,Line,Col,S}.

%% yyaction(Action, TokenLength, TokenChars, TokenLine, TokenCol) ->
%% {token,Token} | {end_token, Token} | skip_token | {error,String}.
%% Generated action function.

yyaction(0, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_0(TokenChars, TokenLine);
yyaction(1, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_1(TokenChars, TokenLine);
yyaction(2, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_2(TokenChars, TokenLine);
yyaction(3, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_3(TokenChars, TokenLine);
yyaction(4, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_4(TokenChars, TokenLine);
yyaction(5, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_5(TokenChars, TokenLine);
yyaction(6, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_6(TokenChars, TokenLine);
yyaction(7, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_7(TokenChars, TokenLine);
yyaction(8, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_8(TokenChars, TokenLine);
yyaction(9, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_9(TokenChars, TokenLine);
yyaction(10, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_10(TokenChars, TokenLine);
yyaction(11, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_11(TokenChars, TokenLine);
yyaction(12, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_12(TokenChars, TokenLine);
yyaction(13, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_13(TokenChars, TokenLine);
yyaction(14, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_14(TokenChars, TokenLine);
yyaction(15, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_15(TokenChars, TokenLine);
yyaction(16, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_16(TokenChars, TokenLine);
yyaction(17, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_17(TokenChars, TokenLine);
yyaction(18, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_18(TokenChars, TokenLine);
yyaction(19, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_19(TokenChars, TokenLine);
yyaction(20, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_20(TokenChars, TokenLine);
yyaction(21, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_21(TokenChars, TokenLine);
yyaction(22, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_22(TokenChars, TokenLine);
yyaction(23, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_23(TokenChars, TokenLine);
yyaction(24, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_24(TokenChars, TokenLine);
yyaction(25, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_25(TokenChars, TokenLine);
yyaction(26, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_26(TokenChars, TokenLine);
yyaction(27, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_27(TokenChars, TokenLine);
yyaction(28, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_28(TokenChars, TokenLine);
yyaction(29, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_29(TokenChars, TokenLine);
yyaction(30, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_30(TokenChars, TokenLine);
yyaction(31, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_31(TokenChars, TokenLine);
yyaction(32, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_32(TokenChars, TokenLine);
yyaction(33, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_33(TokenChars, TokenLine);
yyaction(34, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_34(TokenChars, TokenLine);
yyaction(35, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_35(TokenChars, TokenLine);
yyaction(36, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_36(TokenChars, TokenLine);
yyaction(37, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_37(TokenChars, TokenLine);
yyaction(38, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_38(TokenChars, TokenLine);
yyaction(39, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_39(TokenChars, TokenLine);
yyaction(40, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_40(TokenChars, TokenLine);
yyaction(41, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_41(TokenChars, TokenLine);
yyaction(42, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_42(TokenChars, TokenLine);
yyaction(43, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_43(TokenChars, TokenLine);
yyaction(44, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_44(TokenChars, TokenLine);
yyaction(45, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_45(TokenChars, TokenLine);
yyaction(46, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_46(TokenChars, TokenLine);
yyaction(47, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_47(TokenChars, TokenLine);
yyaction(48, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_48(TokenChars, TokenLine);
yyaction(49, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_49(TokenChars, TokenLine);
yyaction(50, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_50(TokenChars, TokenLine);
yyaction(51, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_51(TokenChars, TokenLine);
yyaction(52, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_52(TokenChars, TokenLine);
yyaction(53, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_53(TokenChars, TokenLine);
yyaction(54, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_54(TokenChars, TokenLine);
yyaction(55, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_55(TokenChars, TokenLine);
yyaction(56, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_56(TokenChars, TokenLine);
yyaction(57, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_57(TokenChars, TokenLine);
yyaction(58, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_58(TokenChars, TokenLine);
yyaction(59, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_59(TokenChars, TokenLine);
yyaction(60, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_60(TokenChars, TokenLine);
yyaction(61, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_61(TokenChars, TokenLine);
yyaction(62, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_62(TokenChars, TokenLine);
yyaction(63, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_63(TokenChars, TokenLine);
yyaction(64, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_64(TokenChars, TokenLine);
yyaction(65, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_65(TokenChars, TokenLine);
yyaction(66, TokenLen, YYtcs, TokenLine, _) ->
    TokenChars = yypre(YYtcs, TokenLen),
    yyaction_66(TokenChars, TokenLine);
yyaction(67, _, _, _, _) ->
    yyaction_67();
yyaction(_, _, _, _, _) -> error.

-compile({inline,yyaction_0/2}).
-file("./priv/obr_lexer.xrl", 117).
yyaction_0(TokenChars, TokenLine) ->
     { token, { t_array, TokenLine, TokenChars } } .

-compile({inline,yyaction_1/2}).
-file("./priv/obr_lexer.xrl", 118).
yyaction_1(TokenChars, TokenLine) ->
     { token, { t_begin, TokenLine, TokenChars } } .

-compile({inline,yyaction_2/2}).
-file("./priv/obr_lexer.xrl", 119).
yyaction_2(TokenChars, TokenLine) ->
     { token, { t_by, TokenLine, TokenChars } } .

-compile({inline,yyaction_3/2}).
-file("./priv/obr_lexer.xrl", 120).
yyaction_3(TokenChars, TokenLine) ->
     { token, { t_case, TokenLine, TokenChars } } .

-compile({inline,yyaction_4/2}).
-file("./priv/obr_lexer.xrl", 121).
yyaction_4(TokenChars, TokenLine) ->
     { token, { t_const, TokenLine, TokenChars } } .

-compile({inline,yyaction_5/2}).
-file("./priv/obr_lexer.xrl", 122).
yyaction_5(TokenChars, TokenLine) ->
     { token, { t_div, TokenLine, TokenChars } } .

-compile({inline,yyaction_6/2}).
-file("./priv/obr_lexer.xrl", 123).
yyaction_6(TokenChars, TokenLine) ->
     { token, { t_do, TokenLine, TokenChars } } .

-compile({inline,yyaction_7/2}).
-file("./priv/obr_lexer.xrl", 124).
yyaction_7(TokenChars, TokenLine) ->
     { token, { t_else, TokenLine, TokenChars } } .

-compile({inline,yyaction_8/2}).
-file("./priv/obr_lexer.xrl", 125).
yyaction_8(TokenChars, TokenLine) ->
     { token, { t_elseif, TokenLine, TokenChars } } .

-compile({inline,yyaction_9/2}).
-file("./priv/obr_lexer.xrl", 126).
yyaction_9(TokenChars, TokenLine) ->
     { token, { t_elsif, TokenLine, TokenChars } } .

-compile({inline,yyaction_10/2}).
-file("./priv/obr_lexer.xrl", 127).
yyaction_10(TokenChars, TokenLine) ->
     { token, { t_end, TokenLine, TokenChars } } .

-compile({inline,yyaction_11/2}).
-file("./priv/obr_lexer.xrl", 128).
yyaction_11(TokenChars, TokenLine) ->
     { token, { t_false, TokenLine, TokenChars } } .

-compile({inline,yyaction_12/2}).
-file("./priv/obr_lexer.xrl", 129).
yyaction_12(TokenChars, TokenLine) ->
     { token, { t_for, TokenLine, TokenChars } } .

-compile({inline,yyaction_13/2}).
-file("./priv/obr_lexer.xrl", 130).
yyaction_13(TokenChars, TokenLine) ->
     { token, { t_if, TokenLine, TokenChars } } .

-compile({inline,yyaction_14/2}).
-file("./priv/obr_lexer.xrl", 131).
yyaction_14(TokenChars, TokenLine) ->
     { token, { t_import, TokenLine, TokenChars } } .

-compile({inline,yyaction_15/2}).
-file("./priv/obr_lexer.xrl", 132).
yyaction_15(TokenChars, TokenLine) ->
     { token, { t_in, TokenLine, TokenChars } } .

-compile({inline,yyaction_16/2}).
-file("./priv/obr_lexer.xrl", 133).
yyaction_16(TokenChars, TokenLine) ->
     { token, { t_is, TokenLine, TokenChars } } .

-compile({inline,yyaction_17/2}).
-file("./priv/obr_lexer.xrl", 134).
yyaction_17(TokenChars, TokenLine) ->
     { token, { t_module, TokenLine, TokenChars } } .

-compile({inline,yyaction_18/2}).
-file("./priv/obr_lexer.xrl", 135).
yyaction_18(TokenChars, TokenLine) ->
     { token, { t_mod, TokenLine, TokenChars } } .

-compile({inline,yyaction_19/2}).
-file("./priv/obr_lexer.xrl", 136).
yyaction_19(TokenChars, TokenLine) ->
     { token, { t_nil, TokenLine, TokenChars } } .

-compile({inline,yyaction_20/2}).
-file("./priv/obr_lexer.xrl", 137).
yyaction_20(TokenChars, TokenLine) ->
     { token, { t_of, TokenLine, TokenChars } } .

-compile({inline,yyaction_21/2}).
-file("./priv/obr_lexer.xrl", 138).
yyaction_21(TokenChars, TokenLine) ->
     { token, { t_or, TokenLine, TokenChars } } .

-compile({inline,yyaction_22/2}).
-file("./priv/obr_lexer.xrl", 139).
yyaction_22(TokenChars, TokenLine) ->
     { token, { t_pointer, TokenLine, TokenChars } } .

-compile({inline,yyaction_23/2}).
-file("./priv/obr_lexer.xrl", 140).
yyaction_23(TokenChars, TokenLine) ->
     { token, { t_procedure, TokenLine, TokenChars } } .

-compile({inline,yyaction_24/2}).
-file("./priv/obr_lexer.xrl", 141).
yyaction_24(TokenChars, TokenLine) ->
     { token, { t_record, TokenLine, TokenChars } } .

-compile({inline,yyaction_25/2}).
-file("./priv/obr_lexer.xrl", 142).
yyaction_25(TokenChars, TokenLine) ->
     { token, { t_repeat, TokenLine, TokenChars } } .

-compile({inline,yyaction_26/2}).
-file("./priv/obr_lexer.xrl", 143).
yyaction_26(TokenChars, TokenLine) ->
     { token, { t_return, TokenLine, TokenChars } } .

-compile({inline,yyaction_27/2}).
-file("./priv/obr_lexer.xrl", 144).
yyaction_27(TokenChars, TokenLine) ->
     { token, { t_to, TokenLine, TokenChars } } .

-compile({inline,yyaction_28/2}).
-file("./priv/obr_lexer.xrl", 145).
yyaction_28(TokenChars, TokenLine) ->
     { token, { t_true, TokenLine, TokenChars } } .

-compile({inline,yyaction_29/2}).
-file("./priv/obr_lexer.xrl", 146).
yyaction_29(TokenChars, TokenLine) ->
     { token, { t_type, TokenLine, TokenChars } } .

-compile({inline,yyaction_30/2}).
-file("./priv/obr_lexer.xrl", 147).
yyaction_30(TokenChars, TokenLine) ->
     { token, { t_var, TokenLine, TokenChars } } .

-compile({inline,yyaction_31/2}).
-file("./priv/obr_lexer.xrl", 148).
yyaction_31(TokenChars, TokenLine) ->
     { token, { t_while, TokenLine, TokenChars } } .

-compile({inline,yyaction_32/2}).
-file("./priv/obr_lexer.xrl", 149).
yyaction_32(TokenChars, TokenLine) ->
     { token, { t_then, TokenLine, TokenChars } } .

-compile({inline,yyaction_33/2}).
-file("./priv/obr_lexer.xrl", 150).
yyaction_33(TokenChars, TokenLine) ->
     { token, { t_until, TokenLine, TokenChars } } .

-compile({inline,yyaction_34/2}).
-file("./priv/obr_lexer.xrl", 154).
yyaction_34(TokenChars, TokenLine) ->
     { token, { t_assert, TokenLine, TokenChars } } .

-compile({inline,yyaction_35/2}).
-file("./priv/obr_lexer.xrl", 177).
yyaction_35(TokenChars, TokenLine) ->
     { token, { t_plus, TokenLine, TokenChars } } .

-compile({inline,yyaction_36/2}).
-file("./priv/obr_lexer.xrl", 178).
yyaction_36(TokenChars, TokenLine) ->
     { token, { t_minus, TokenLine, TokenChars } } .

-compile({inline,yyaction_37/2}).
-file("./priv/obr_lexer.xrl", 179).
yyaction_37(TokenChars, TokenLine) ->
     { token, { t_mul, TokenLine, TokenChars } } .

-compile({inline,yyaction_38/2}).
-file("./priv/obr_lexer.xrl", 180).
yyaction_38(TokenChars, TokenLine) ->
     { token, { t_divide, TokenLine, TokenChars } } .

-compile({inline,yyaction_39/2}).
-file("./priv/obr_lexer.xrl", 181).
yyaction_39(TokenChars, TokenLine) ->
     { token, { t_tilda, TokenLine, TokenChars } } .

-compile({inline,yyaction_40/2}).
-file("./priv/obr_lexer.xrl", 182).
yyaction_40(TokenChars, TokenLine) ->
     { token, { t_and, TokenLine, TokenChars } } .

-compile({inline,yyaction_41/2}).
-file("./priv/obr_lexer.xrl", 183).
yyaction_41(TokenChars, TokenLine) ->
     { token, { t_ddot, TokenLine, TokenChars } } .

-compile({inline,yyaction_42/2}).
-file("./priv/obr_lexer.xrl", 184).
yyaction_42(TokenChars, TokenLine) ->
     { token, { t_dot, TokenLine, TokenChars } } .

-compile({inline,yyaction_43/2}).
-file("./priv/obr_lexer.xrl", 185).
yyaction_43(TokenChars, TokenLine) ->
     { token, { t_comma, TokenLine, TokenChars } } .

-compile({inline,yyaction_44/2}).
-file("./priv/obr_lexer.xrl", 186).
yyaction_44(TokenChars, TokenLine) ->
     { token, { t_semicolon, TokenLine, TokenChars } } .

-compile({inline,yyaction_45/2}).
-file("./priv/obr_lexer.xrl", 187).
yyaction_45(TokenChars, TokenLine) ->
     { token, { t_vline, TokenLine, TokenChars } } .

-compile({inline,yyaction_46/2}).
-file("./priv/obr_lexer.xrl", 188).
yyaction_46(TokenChars, TokenLine) ->
     { token, { t_lpar, TokenLine, TokenChars } } .

-compile({inline,yyaction_47/2}).
-file("./priv/obr_lexer.xrl", 189).
yyaction_47(TokenChars, TokenLine) ->
     { token, { t_rpar, TokenLine, TokenChars } } .

-compile({inline,yyaction_48/2}).
-file("./priv/obr_lexer.xrl", 190).
yyaction_48(TokenChars, TokenLine) ->
     { token, { t_lbrack, TokenLine, TokenChars } } .

-compile({inline,yyaction_49/2}).
-file("./priv/obr_lexer.xrl", 191).
yyaction_49(TokenChars, TokenLine) ->
     { token, { t_rbrack, TokenLine, TokenChars } } .

-compile({inline,yyaction_50/2}).
-file("./priv/obr_lexer.xrl", 192).
yyaction_50(TokenChars, TokenLine) ->
     { token, { t_lbrace, TokenLine, TokenChars } } .

-compile({inline,yyaction_51/2}).
-file("./priv/obr_lexer.xrl", 193).
yyaction_51(TokenChars, TokenLine) ->
     { token, { t_rbrace, TokenLine, TokenChars } } .

-compile({inline,yyaction_52/2}).
-file("./priv/obr_lexer.xrl", 194).
yyaction_52(TokenChars, TokenLine) ->
     { token, { t_assign, TokenLine, TokenChars } } .

-compile({inline,yyaction_53/2}).
-file("./priv/obr_lexer.xrl", 195).
yyaction_53(TokenChars, TokenLine) ->
     { token, { t_colon, TokenLine, TokenChars } } .

-compile({inline,yyaction_54/2}).
-file("./priv/obr_lexer.xrl", 196).
yyaction_54(TokenChars, TokenLine) ->
     { token, { t_arrow, TokenLine, TokenChars } } .

-compile({inline,yyaction_55/2}).
-file("./priv/obr_lexer.xrl", 197).
yyaction_55(TokenChars, TokenLine) ->
     { token, { t_equ, TokenLine, TokenChars } } .

-compile({inline,yyaction_56/2}).
-file("./priv/obr_lexer.xrl", 198).
yyaction_56(TokenChars, TokenLine) ->
     { token, { t_sharp, TokenLine, TokenChars } } .

-compile({inline,yyaction_57/2}).
-file("./priv/obr_lexer.xrl", 199).
yyaction_57(TokenChars, TokenLine) ->
     { token, { t_lesseq, TokenLine, TokenChars } } .

-compile({inline,yyaction_58/2}).
-file("./priv/obr_lexer.xrl", 200).
yyaction_58(TokenChars, TokenLine) ->
     { token, { t_moreeq, TokenLine, TokenChars } } .

-compile({inline,yyaction_59/2}).
-file("./priv/obr_lexer.xrl", 201).
yyaction_59(TokenChars, TokenLine) ->
     { token, { t_less, TokenLine, TokenChars } } .

-compile({inline,yyaction_60/2}).
-file("./priv/obr_lexer.xrl", 202).
yyaction_60(TokenChars, TokenLine) ->
     { token, { t_more, TokenLine, TokenChars } } .

-compile({inline,yyaction_61/2}).
-file("./priv/obr_lexer.xrl", 208).
yyaction_61(TokenChars, TokenLine) ->
     { token, { integer_hex, TokenLine, intwr_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_62/2}).
-file("./priv/obr_lexer.xrl", 209).
yyaction_62(TokenChars, TokenLine) ->
     { token, { integer_dec, TokenLine, int_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_63/2}).
-file("./priv/obr_lexer.xrl", 210).
yyaction_63(TokenChars, TokenLine) ->
     { token, { real, TokenLine, TokenChars } } .

-compile({inline,yyaction_64/2}).
-file("./priv/obr_lexer.xrl", 211).
yyaction_64(TokenChars, TokenLine) ->
     { token, { string, TokenLine, str_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_65/2}).
-file("./priv/obr_lexer.xrl", 213).
yyaction_65(TokenChars, TokenLine) ->
     { token, { letter, TokenLine, id_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_66/2}).
-file("./priv/obr_lexer.xrl", 214).
yyaction_66(TokenChars, TokenLine) ->
     { token, { digit, TokenLine, id_validate (TokenChars, TokenLine) } } .

-compile({inline,yyaction_67/0}).
-file("./priv/obr_lexer.xrl", 217).
yyaction_67() ->
     skip_token .
-file("/home/sea/.asdf/installs/erlang/27.2.4/lib/parsetools-2.6/include/leexinc.hrl", 344).
